DROP TABLE IF EXISTS genre_list;
DROP TABLE IF EXISTS likes_list;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS friends_list;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS rating;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS rating
(
    rating_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_code VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS films
(
    film_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR NOT NULL,
    description VARCHAR(200),
    releaseDate DATE,
    duration    INT,
    rating      INT REFERENCES rating (rating_id)
);

CREATE TABLE IF NOT EXISTS genre
(
    genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS genre_list
(
    film_id BIGINT REFERENCES films(film_id) NOT NULL ,
    genre_id INT REFERENCES genre(genre_id)NOT NULL ,
    UNIQUE (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR NOT NULL ,
    login VARCHAR NOT NULL ,
    name VARCHAR,
    birthday DATE
);

CREATE TABLE IF NOT EXISTS likes_list
(
    film_id BIGINT REFERENCES films(film_id),
    user_id BIGINT REFERENCES users(user_id),
    UNIQUE (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friends_list
(
    user_id BIGINT REFERENCES users(user_id),
    friend_id BIGINT REFERENCES users(user_id),
    confirmed BOOLEAN,
    UNIQUE (user_id, friend_id)
)
